name: Ejecutar exportar_Inventarios_Totalizado.py

on:
  workflow_dispatch: # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequear el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Cambiá la versión si usás otra

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          pip install openpyxl

      # 4. Ejecutar el script
      - name: Run exportar_Inventarios_Totalizado.py
        run: |
          python script/exportar_Inventarios_Totalizado.py

      # 5. Subir el archivo Excel generado como artefacto
      - name: Upload Excel artifact
        uses: actions/upload-artifact@v3
        with:
          name: inventario_totalizado
          path: databases/inventario_totalizado/*.xlsx


